### PR TITLE
Appearance shit

### PR DESCRIPTION
**Pull request by nullpixel**
Removed most single code blocks and bolds as they are hard on the eyes.

### CODE REVIEW

**Comment by Lisiano256** [comment]
The code in the current state will completely break formatting. Unsafe to merge.

**Comment by k1n3t1c** [comment]
@nullpixel1 Pull github, just updated by adding logging to all event handlers.

**Comment by nullpixel** [comment]
Ok, I'll attempt to fix this shit in a minute too @fkndean

**Comment by nullpixel** [comment]
Closed, no time to fix this.

**Pull request closed without merging**
